/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package User.Registration.Test;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;

public class FirstNameTest {
    @Test 
    	public void givenFirstName_WhenProper_ShouldReturnTrue() {
        FirstName classUnderTest = new FirstName();
        boolean result = classUnderTest.firstName("Suraj");
        Assert.assertEquals(true, result);
    }
    
    	public void givenFirstName_WhenNotProper_ShouldReturnFalse() {
        FirstName classUnderTest = new FirstName();
        boolean result = classUnderTest.firstName("suraj");
        Assert.assertEquals(false, result);
    }
}